services:
  - type: web
    name: app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn clone.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        generateValue: true
